### ISSUE TITLE
missing exe in focalcod-win32-0.1.0_base.zip

### ISSUE THREAD

**Issue by pcscote** [cgottheimer/focalcod#1]
Hello Christophe,
This is just to inform you that you have forgotten to include the win32 executable in the focalcod-win32-0.1.0_base.zip file, like you did in the asmnut-win32-0.40.0_base.zip file.
Both posted on hp41.org site.
Best regards,
Sylvain

**Comment by cgottheimer** [comment]
Hello, Sylvain

I removed them because they are not working under Windows. I made a patch
recently and a working version is now available to my github (commit ID:*
6ae6db120422d749ffd0cceba0ad8134ef0a71ab*)

I have a friend who will test them soon, and if it is working, I will
publish them to Warren site's with the new sources.
Please, find in attachment a ZIP I build for you. This is still in test, so
do not hesitate to report bugs to me.

The MD5SUM for the executables:
*0b5d7ef2a546dbcad477d3d6ec0e79b8  focalcod/focalcod_exe*
*6328798959224ec021d230002e52b300  focalcod/focaldecod_exe*
*38ebfc67a6ba09210fee16a491f5c9cd  focalcod/focalxrom_exe*

You will have to rename the *_exe* to *.exe* to execute them.

Thank you for using :)

Best regards,

Christophe

2016-07-01 20:26 GMT+02:00 pcscote <notifications@github.com>:

**Comment by cgottheimer** [comment]
The problem for Windows32 is in the binary files generation or reading. I opened them with fopen() and added the mode "b" to specify a binary file. But, it seems that this mode is discarded and so binary files are opened as text files. As funny example, coding the LBL 09 (code 0xa) will add a LBL 12 (code 0xd) before it !
To solve this, I call _setmode( _fileno(fd), _O_BINARY ). With this, I hope it is working.

**Comment by cgottheimer** [comment]
RELEASE 0.1.1 is working under Windows32 and Linux
